# ActionScript sources for skyui/configpanel.swf
# Auto-generated from SWF decompilation

set(skyui_configpanel_SOURCES
    ${AS_SOURCE_DIR}/Common/Components/CrossPlatformButtons.as
    ${AS_SOURCE_DIR}/Common/Shared/ButtonChange.as
    ${AS_SOURCE_DIR}/Common/Shared/GlobalFunc.as
    ${AS_SOURCE_DIR}/Common/skyui/components/ButtonPanel.as
    ${AS_SOURCE_DIR}/Common/skyui/components/MappedButton.as
    ${AS_SOURCE_DIR}/Common/skyui/components/Slider.as
    ${AS_SOURCE_DIR}/Common/skyui/components/colorswatch/ColorSquare.as
    ${AS_SOURCE_DIR}/Common/skyui/components/colorswatch/ColorSwatch.as
    ${AS_SOURCE_DIR}/Common/skyui/components/dialog/BasicDialog.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/BSList.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/BasicEnumeration.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/BasicList.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/BasicListEntry.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/ButtonListEntry.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/EntryClipManager.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/IEntryEnumeration.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/IListProcessor.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/ListState.as
    ${AS_SOURCE_DIR}/Common/skyui/components/list/ScrollingList.as
    ${AS_SOURCE_DIR}/Common/skyui/defines/Input.as
    ${AS_SOURCE_DIR}/Common/skyui/util/ColorFunctions.as
    ${AS_SOURCE_DIR}/Common/skyui/util/DialogManager.as
    ${AS_SOURCE_DIR}/Common/skyui/util/GlobalFunctions.as
    ${AS_SOURCE_DIR}/Common/skyui/util/Translator.as
    ${AS_SOURCE_DIR}/Common/skyui/util/Tween.as
    ${AS_SOURCE_DIR}/ModConfigPanel/ColorDialog.as
    ${AS_SOURCE_DIR}/ModConfigPanel/ConfigPanel.as
    ${AS_SOURCE_DIR}/ModConfigPanel/MenuDialog.as
    ${AS_SOURCE_DIR}/ModConfigPanel/MessageDialog.as
    ${AS_SOURCE_DIR}/ModConfigPanel/ModListPanel.as
    ${AS_SOURCE_DIR}/ModConfigPanel/MultiColumnScrollBar.as
    ${AS_SOURCE_DIR}/ModConfigPanel/MultiColumnScrollingList.as
    ${AS_SOURCE_DIR}/ModConfigPanel/OptionDialog.as
    ${AS_SOURCE_DIR}/ModConfigPanel/OptionsListEntry.as
    ${AS_SOURCE_DIR}/ModConfigPanel/SliderDialog.as
    ${AS_SOURCE_DIR}/ModConfigPanel/TextInputDialog.as
)
